global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'bsopt-services'
    static_configs:
      - targets: ['api:8000', 'worker-ml:8000', 'worker-pricing:8000']
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
  - job_name: 'github-exporter'
    static_configs:
      - targets: ['github-exporter:9101']
